### ISSUE TITLE
Expose `tags` and `sig` methods for `Note`

### ISSUE THREAD

**Issue by yukibtc** [damus-io/nostrdb-rs#2]
Hey, I've started implementing the `NostrDatabase` trait for `nostrdb`, to allow to use it with the `nostr-sdk` (or sub-crate) but I noticed that the `Note` struct doesn't have `tags` and `sig` methods. 

https://github.com/rust-nostr/nostr/pull/292

**Comment by jb55** [comment]
On Wed, Feb 14, 2024 at 02:07:33AM -0800, Yuki Kishimoto wrote:
>Hey, I've started implementing the `NostrDatabase` trait for `nostrdb`,
>to allow to use it with the `nostr-sdk` (or sub-crate) but I noticed
>that the `Note` struct doesn't have `tags` and `sig` methods.

not sure when I will get to this, I imagine soon since I will need to
access tags in notedeck.

**Comment by jb55** [comment]
published @ v0.3.0
