### ISSUE TITLE
Infinite tags loop

### ISSUE THREAD

**Issue by yukibtc** [damus-io/nostrdb-rs#5]
I just noticed that `note.tags.iter()` never return `None` when calling `.next()`, causing an infinite loop.

To reproduce, add `assert!(tags_iter.next().is_none())` at the end of `tag_iter_works` test.

**Comment by jb55** [comment]
I didn't test this too much yet so thanks for being the guinea pig. fixing.

**Comment by jb55** [comment]
published to v0.3.1
